drivers: gpu: panel_decon: Rename `in_range()` macro
After [1], it conflicts with the kernel's minmax.h definition of it.

../drivers/gpu/drm/samsung/panel_decon/decon_dimming.h:251:9: error: 'in_range' macro redefined [-Werror,-Wmacro-redefined]
  251 | #define in_range(i, r)                                  \
      |         ^
../include/linux/minmax.h:298:9: note: previous definition is here
  298 | #define in_range(val, start, len)                                       \
      |         ^
1 error generated.

[1] aosp-mirror/kernel_common@6183c65

Change-Id: I8386e299212603403d7bae7f89aabc7dffef683d
Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: Majaahh <maja.blaszczak@proton.me>